update

diff --git a/.github/workflows/az-vote-cicd.yml b/.github/workflows/az-vote-cicd.yml
--- a/.github/workflows/az-vote-cicd.yml
+++ b/.github/workflows/az-vote-cicd.yml
@@ -139,7 +139,6 @@ jobs:
       with:
         app-id: ${{ secrets.GH_ID_01 }}
         private-key: ${{ secrets.GH_KEY_01 }}
-        owner: ${{ github.repository_owner }}
 
     - name: Use the token
       env:
@@ -148,89 +147,112 @@ jobs:
         gh api octocat
         gh repo view manojtjacobs/gitops-code --json nameWithOwner,defaultBranchRef
 
-    - name: Create PR
+    - name: Use the token
       env:
-        GH_TOKEN: ${{ steps.app-token.outputs.token }}
-        # TOKEN1: "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"
-        MANIFESTS_FOLDER: arc-cicd-cluster
-        MANIFESTS_REPO: https://github.com/manojtjacobs/gitops-code
-        MANIFESTS_BRANCH: master
-        ENVIRONMENT_NAME: Dev
-        # BACKEND_IMAGE: 6.0.8
+        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
       run: |
-        echo "List input params"
-        SOURCE_FOLDER=${{ github.workspace }}/gen_manifests
-        echo $SOURCE_FOLDER
-        DEST_FOLDER=$MANIFESTS_FOLDER
-        echo $DEST_FOLDER
-        DEST_REPO=$MANIFESTS_REPO
-        echo $DEST_REPO
-        DEST_BRANCH=$(echo $release_prefix)$MANIFESTS_BRANCH
-        echo $DEST_BRANCH
-        DEPLOY_ID=$GITHUB_RUN_ID
-        echo $DEPLOY_ID
-        ENV_NAME=$ENVIRONMENT_NAME
-        echo $ENV_NAME
-        TOKEN=$GH_TOKEN
-        echo "$GH_TOKEN"
-        echo "end of list"
-
-        set -euo pipefail  # fail on error
-
-        pr_user_name="Git Ops"
-        pr_user_email="agent@gitops.com"
-
-        pr_user_name="manojtjacobs"
-        pr_user_email="manjacob@microsoft.com.com"
-
-        git config --global user.email $pr_user_email
-        git config --global user.name $pr_user_name
-
-        # Clone manifests repo
-        echo "Clone manifests repo"
-        repo_url="${DEST_REPO#http://}"
-        repo_url="${DEST_REPO#https://}"
-        repo_url="https://automated:$TOKEN@$repo_url.git"
+        # Set up git configuration
+        git config --global user.name "Manoj Jacob"
+        git config --global user.email "manjacob@microsoft.com"
         
-        # repo_url="https://github.com/manojtjacobs/gitops-code.git"
+        # Clone the repository
+        git clone https://github.com/manojtjacobs/gitops-code.git
+                
+        # Make changes (e.g., create or modify files)
+        echo "New content" > newfile.txt
         
-        echo "git clone $repo_url -b $DEST_BRANCH --depth 1 --single-branch"
-        git clone $repo_url -b $DEST_BRANCH --depth 1 --single-branch
-        repo=${DEST_REPO##*/}
-        repo_name=${repo%.*}
-        cd "$repo_name"
-        echo "git status"
-        git status
+        # Stage changes
+        git add .
+        
+        # Commit changes
+        git commit -m "Add newfile.txt"
+        
+        # Push changes to a different branch
+        git push origin my-feature-branch
 
-        # Create a new branch 
-        deploy_branch_name=deploy/$DEPLOY_ID/$BACKEND_IMAGE/$DEST_BRANCH
+    # - name: Create PR
+    #   env:
+    #     GH_TOKEN: ${{ steps.app-token.outputs.token }}
+    #     # TOKEN1: "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"
+    #     MANIFESTS_FOLDER: arc-cicd-cluster
+    #     MANIFESTS_REPO: https://github.com/manojtjacobs/gitops-code
+    #     MANIFESTS_BRANCH: master
+    #     ENVIRONMENT_NAME: Dev
+    #     # BACKEND_IMAGE: 6.0.8
+    #   run: |
+    #     echo "List input params"
+    #     SOURCE_FOLDER=${{ github.workspace }}/gen_manifests
+    #     echo $SOURCE_FOLDER
+    #     DEST_FOLDER=$MANIFESTS_FOLDER
+    #     echo $DEST_FOLDER
+    #     DEST_REPO=$MANIFESTS_REPO
+    #     echo $DEST_REPO
+    #     DEST_BRANCH=$(echo $release_prefix)$MANIFESTS_BRANCH
+    #     echo $DEST_BRANCH
+    #     DEPLOY_ID=$GITHUB_RUN_ID
+    #     echo $DEPLOY_ID
+    #     ENV_NAME=$ENVIRONMENT_NAME
+    #     echo $ENV_NAME
+    #     TOKEN=$GH_TOKEN
+    #     echo "$GH_TOKEN"
+    #     echo "end of list"
 
-        echo "Create a new branch $deploy_branch_name"
-        git checkout -b $deploy_branch_name
+    #     set -euo pipefail  # fail on error
 
-        # Add generated manifests to the new deploy branch
-        mkdir -p $DEST_FOLDER
-        cp -r $SOURCE_FOLDER/* $DEST_FOLDER/
-        git add -A
-        git status
-        if [[ `git status --porcelain | head -1` ]]; then
-            git commit -m "deployment $DEPLOY_ID"
-            # repo_url=$DEST_REPO
-            ls -l
-            # Push to the deploy branch 
-            echo "Push to the deploy branch $deploy_branch_name"
-            echo "git push --set-upstream $repo_url $deploy_branch_name"
-            # git push --set-upstream $repo_url $deploy_branch_name
-            # Create a PR 
-            echo "Create a PR to $DEST_BRANCH"
+    #     pr_user_name="Git Ops"
+    #     pr_user_email="agent@gitops.com"
+
+    #     pr_user_name="manojtjacobs"
+    #     pr_user_email="manjacob@microsoft.com.com"
+
+    #     git config --global user.email $pr_user_email
+    #     git config --global user.name $pr_user_name
+
+    #     # Clone manifests repo
+    #     echo "Clone manifests repo"
+    #     repo_url="${DEST_REPO#http://}"
+    #     repo_url="${DEST_REPO#https://}"
+    #     repo_url="https://automated:$TOKEN@$repo_url.git"
+        
+    #     # repo_url="https://github.com/manojtjacobs/gitops-code.git"
+        
+    #     echo "git clone $repo_url -b $DEST_BRANCH --depth 1 --single-branch"
+    #     git clone $repo_url -b $DEST_BRANCH --depth 1 --single-branch
+    #     repo=${DEST_REPO##*/}
+    #     repo_name=${repo%.*}
+    #     cd "$repo_name"
+    #     echo "git status"
+    #     git status
+
+    #     # Create a new branch 
+    #     deploy_branch_name=deploy/$DEPLOY_ID/$BACKEND_IMAGE/$DEST_BRANCH
+
+    #     echo "Create a new branch $deploy_branch_name"
+    #     git checkout -b $deploy_branch_name
+
+    #     # Add generated manifests to the new deploy branch
+    #     mkdir -p $DEST_FOLDER
+    #     cp -r $SOURCE_FOLDER/* $DEST_FOLDER/
+    #     git add -A
+    #     git status
+    #     if [[ `git status --porcelain | head -1` ]]; then
+    #         git commit -m "deployment $DEPLOY_ID"
+    #         # repo_url=$DEST_REPO
+    #         ls -l
+    #         # Push to the deploy branch 
+    #         echo "Push to the deploy branch $deploy_branch_name"
+    #         echo "git push --set-upstream $repo_url $deploy_branch_name"
+    #         # git push --set-upstream $repo_url $deploy_branch_name
+    #         # Create a PR 
+    #         echo "Create a PR to $DEST_BRANCH"
             
-            owner_repo="${DEST_REPO#https://github.com/}"
-            echo $owner_repo
-            # GITHUB_TOKEN=$TOKEN
-            # echo $GITHUB_TOKEN | gh auth login --with-token
-            repo_url="https://github.com/manojtjacobs/gitops-code.git"
-            gh pr create --base $DEST_BRANCH --head $deploy_branch_name --title "deployment '$DEPLOY_ID'" --body "Deploy to '$ENV_NAME'"
-        fi 
+    #         owner_repo="${DEST_REPO#https://github.com/}"
+    #         echo $owner_repo
+    #         # GITHUB_TOKEN=$TOKEN
+    #         # echo $GITHUB_TOKEN | gh auth login --with-token
+    #         repo_url="https://github.com/manojtjacobs/gitops-code.git"
+    #         gh pr create --base $DEST_BRANCH --head $deploy_branch_name --title "deployment '$DEPLOY_ID'" --body "Deploy to '$ENV_NAME'"
+    #     fi 
 
     # - name: Create PR
     #   env:
